language: go
go:
- 1.6
- 1.7.x
- master
before_install:
- go get github.com/golang/lint/golint
- go get github.com/gordonklaus/ineffassign
- go get github.com/fzipp/gocyclo
- go get -u github.com/client9/misspell/cmd/misspell
script:
- "./pre-commit"
- ls -l
- go build
- ls -l
- go build
deploy:
  provider: releases
  api_key:
    secure: ZSqZx+Ej1mFm5vFjAYvBmVVUfulT7xaRkjVL3Wh13N3pVroUtRi6mwAHfcXdIprGa1rToCIP66BQD8q26DLe2kwEYNJK2gtvbjNzsOPJgmtLoBW7GKW0p9gm0MXFCNmwVwGEJUpTvi4aWNIHIVqrLrAA2adrfF1eIepBOYB5Iu6wDqa0WKnbuVd87+Bx17XquhNZCETKBUpvAL4v3D2shkxz/twOJnVTms5JuJUZ5mKNZo99PlsoW1GtfwKHDNw6ChE8pl96cCvLQz4AyBxF8BIDfNSWW9QrcxyNGzesKa2+Q5IcBPQ7v/RfuEnVctiCQqvnrZ65cKvn2edbH1j35gTRINGo9lzHWNqGGPKhAbiloeKIRXV/6L3ClewwTY4w+rTwxy8Ted4MWcGSAdMdVlodIXT7PGJ1IdJy16iw23DND4PqNEcwJyvYypoXFJ0vPz3yG8CtM5KI7C+2wNRVnm9J46m430wjlqa19YI/1DlFS+iE2KYAVvtVAJfS/fuJy6Y/db8rh2LqW2OaOMX5al8iT3dSaqkQjxiOfynITJQXiYrsoFpYoDEDbkvTG6L6oaDq3kudCvcHeYugAm61TORCKeDPtIZoInZUhw+in3DTN9zv/qJ7HHQ5LBjFwyggRGSmP33A6tvKxyXhkRXH/6UzLC0yT80lWAkEiuabbmw=
  file: ci-test
  on:
    repo: jandelgado/ci-test
