language: go

go:
  - 1.6
  - 1.7.x
  - master

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/fzipp/gocyclo
  - go get -u github.com/client9/misspell/cmd/misspell

script:
  - ./pre-commit

